community_name: "TrackForge"
community_tagline: "Where musicians, fans and artists hangout!"
community_description:  "A place for independent artists to meet, collaborate, jam and play!"
support_email:  "support@trackforge.com"
meta_description: 'A description of your community for use in META tags.'
meta_keywords: 'keywords for use in META tags'
sections_enabled: ['photos', 'posts', 'clippings', 'contests', 'categories', 'events']
show_advertising: true
closed_beta_mode: false
show_footer_content: false
# The label you use for 'staff' writers (featured writer, staff, pro, etc.)
featured_writer_label: 'Featured Artist'

photo:
  missing_thumb: '/images/theme/default_avatar_thumb.png'
  missing_medium: "/images/theme/default_avatar_medium.png"
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    #size in megabytes
    max_size: 3
    thumbnails: {thumb: "58x58!", medium: "220x320!", large: "664>"}
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 's3'
    processor: 'MiniMagick'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

audio:
  attachment_fu_options:
    resize_to: "1x1"
    min_size: 1    
    #size in megabytes
    max_size: 10
    #options - 's3', 'file_system', 'db_system' - see attachment_fu for details
    storage: 's3'
    content_type: ['audio/mpeg', 'audio/mpg', 'audio/x-ms-wma', 'application/ogg', 'audio/x-wav', 'audio/mid']

feature:
  use_thumbs: true
  dimensions: [300, 300]
  attachment_fu_options:
    resize_to: "300x300"
    min_size: 1    
    max_size: 1
    #thumbnails:     
    storage: 's3'
    processor: 'MiniMagick'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']
        
clipping:
  attachment_fu_options:
    resize_to: "465>"
    min_size: 1    
    max_size: 3
    thumbnails: {thumb: "100x100!", medium_square: "200x200!", medium: "200>"}
    storage: 's3'
    processor: 'MiniMagick'
    content_type: ['image/jpg', 'image/jpeg', 'image/pjpeg', 'image/gif', 'image/png', 'image/x-png']

theme: trackforge